# Generated by Django 4.0.6 on 2022-08-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('site_link', models.CharField(max_length=500)),
                ('img', models.ImageField(upload_to='pics')),
                ('github_link', models.CharField(max_length=500)),
            ],
        ),
    ]
